### ISSUE TITLE
Change READ.ME from "sendData" & "sendString" to "send"

### ISSUE THREAD

**Issue by Loag** [facebookincubator/SocketRocket#484]
In READ.ME under API the two methods for sending are "sendData" and "sendString" but in the current pod the only method available is just simply "send"

**Comment by MudassirAsghar22** [comment]
it shows me error No visible @interface for 'SRWebSocket' declares the selector 'sendString:error:'
when i used  [_webSocket sendString:message error:NULL]; or  [_webSocket sendData:message error:NULL];
