### ISSUE TITLE
is 0.6.1 available in pods?

### ISSUE THREAD

**Issue by skurgansky-sugarcrm** [facebookincubator/SocketRocket#666]
[!] CocoaPods could not find compatible versions for pod "SocketRocket":
  In Podfile:
    React-Core/RCTWebSocket (from `../node_modules/react-native/`) was resolved to 0.72.1, which depends on
      SocketRocket (= 0.6.1)

None of your spec sources contain a spec satisfying the dependency: `SocketRocket (= 0.6.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by cipolleschi** [comment]
Hi @skurgansky-sugarcrm the error is also explaining what you have to do:

> `out-of-date source repos which you can update with pod repo update or with pod install --repo-update.`

When you install Cocoapods, you also clone the Cocoapods spec repository (a repository with all the podspecs) locally.
When a new version of a pod is released, Cocoapods only updates the central repository with the new podspec (it can't go to your local machine and update it for you).
So, the error you are facing, is that you have a local versions of the spec which does not know that it exists a version 0.6.1 of SocketRocket, and the installation fails.

By running `pod repo update` you will update your local clone of the spec repository, fetching the new spec for SocketRocket 0.6.1.
After that, you can go back using `pod install` normally.

Hope this helps!

**Comment by skurgansky-sugarcrm** [comment]
it helped. thanks
i tried to do it before but it was emitting an error. same as `pod install --repo-update`
I used to have ruby 2.7.5 then i switched ruby to 3.1.2 and installed cocoapods. After i got same error and posted this issue. Today pod repo update worked for me..
