### ISSUE TITLE
Add SocketRocket.podspec of 0.7.0 version to https://github.com/CocoaPods/Specs.git

### ISSUE THREAD

**Issue by abjox** [facebookincubator/SocketRocket#674]
Please, add to https://github.com/CocoaPods/Specs.git specs of newest version 0.7.0

Currently there is no ability to use 0.7.0 version from CocoaPods/Specs.

Directly specify source in Podfile is not correct option for me!

**Comment by abjox** [comment]
@nlutsenko @mikelikespie @dfed Please, help to resolve that issue.

**Comment by dfed** [comment]
Going to leave this to @nlutsenko. Mike and I haven't been owners of this repo since ~2015.

**Comment by abjox** [comment]
Hi, closing this issue. Sorry for inconvenience. https://github.com/CocoaPods/Specs/blob/master/Specs/a/9/3/SocketRocket/0.7.0/SocketRocket.podspec.json 0.7.0 available
