### ISSUE TITLE
'OSSpinLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock() from <os/lock.h> instead

### ISSUE THREAD

**Issue by funnel20** [facebookincubator/SocketRocket#678]
After installing version 0.7.0 via Cocoapods, Xcode 15.3 shows the following 5 deprecations in file "SRWebSocket.m":
```
'OSSpinLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock() from <os/lock.h> instead
'OSSpinLockLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock_lock() from <os/lock.h> instead
'OSSpinLockLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock_lock() from <os/lock.h> instead
'OSSpinLockLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock_lock() from <os/lock.h> instead
'OSSpinLockUnlock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock_unlock() from <os/lock.h> instead
```

These occur in `setReadyState:` and `readyState`.

<img width="767" alt="Screenshot 2024-05-08 at 19 16 43" src="https://github.com/facebookincubator/SocketRocket/assets/2139844/f2a70195-aa0b-49b1-b85c-cb82e45e1644">

Please resolve, here is an idea: https://stackoverflow.com/a/59004450/2439941

**Comment by funnel20** [comment]
@nlutsenko Thank you for incorporating my proposed changes in version [0.7.1.](https://github.com/facebookincubator/SocketRocket/releases/tag/0.7.1)
I have verified the update and the warnings are no longer shown in Xcode 👍✅

This means that this issue can be closed.

**Comment by nlutsenko** [comment]
No problem, thank you for making it better.
I used an internal reference we had that was fixing the similar case, and then also included a bit more changes, like fixing nullability completeness, but happy 0.7.1 is finally out.
