### ISSUE TITLE
XCode 16 compile error

### ISSUE THREAD

**Issue by nastasiupta** [facebookincubator/SocketRocket#691]
![Screenshot 2024-09-17 at 11 48 41](https://github.com/user-attachments/assets/27d5cd03-b6c8-4cb6-9809-0f42f93d8c10)

Just donwloaded XCode 16 to check one of my projects and I received the following errors.
Everything worked and works fine on XCode 15.4.
I cleaned, reset SPM cached etc and I have the same issue.

**Comment by cipolleschi** [comment]
Can you provide a project with a reroducer? We use Socket Rocket in many React Native apps and it's building fine for us.

**Comment by cipolleschi** [comment]
Can we close this, then? 🙏
